# Site settings
title: paloderosa
email: veintequetzales@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Paying the rent with a bit of math
baseurl:  # the subpath of your site, e.g. /blog/
url:  paloderosa.github.io
twitter_username: twitter_username
github_username:  paloderosa

# Build settings
markdown: kramdown

highlighter: rouge

plugins: [jekyll-paginate]

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


